data:
    image: busybox
    volumes:
        - ${PINTUSHI_DIR}:/var/www/pintushi
        - ~/.ssh/${SSH_PRIVATE_KEY_NAME}:/root/.ssh/${SSH_PRIVATE_KEY_NAME}:ro
        - ~/.composer:/root/.composer
        - ~/.cache/yarn:/usr/local/share/.cache/yarn
        - /tmpfs
        
mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: pintushi_dev
        MYSQL_USER: pintushi
        MYSQL_PASSWORD: pintushi

php:
    image: "videni/php-fpm-node"
    working_dir: /var/www/pintushi
    volumes_from:
        - data
    links:
        - mysql
    mem_limit: 2000000000
    env_file:
        - .env
