data:
    image: busybox
    volumes:
        - ${PINTUSHI_DIR}:/var/www/pintushi
        - ~/.ssh/${SSH_PRIVATE_KEY_NAME}:/root/.ssh/${SSH_PRIVATE_KEY_NAME}:ro
        - ~/.composer:/root/.composer
        - ~/.cache/yarn:/usr/local/share/.cache/yarn
        - /tmpfs

nginx:
    image: nginx
    links:
        - php
    volumes_from:
        - data
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
          - "8080:80"

mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: pintushi_dev
        MYSQL_USER: pintushi
        MYSQL_PASSWORD: pintushi

php:
    build: php
    working_dir: /var/www/pintushi
    volumes_from:
        - data
    links:
        - mysql
    mem_limit: 2000000000
    env_file:
        - .env
