version: '3.2'

services:
    db:
        container_name: pintushi-db
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: pintushi
            POSTGRES_PASSWORD: pintushi

    application:
        container_name: pintushi-application
        build:
            context: .
            dockerfile: ./Dockerfile
        working_dir: /var/www/pintushi
        volumes:
            - ${PINTUSHI_DIR}:/var/www/pintushi
            - ~/.ssh/${SSH_PRIVATE_KEY_NAME}:/root/.ssh/git:ro
            - ~/.composer:/root/.composer
            - /tmpfs
        depends_on:
            - db
        ports:
          - 9090:80
        env_file:
            - .env