version: '3.2'

services:
    mysql:
        container_name: pintushi-mysql
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pintushi_dev
            MYSQL_USER: pintushi
            MYSQL_PASSWORD: pintushi

    application:
        container_name: pintushi-application
        build:
            context: .
            dockerfile: ./Dockerfile
        working_dir: /var/www/pintushi
        volumes:
            - ${PINTUSHI_ADMIN_DIR}:/var/www/pintushi
            - ~/.ssh/${SSH_PRIVATE_KEY_NAME}:/root/.ssh/${SSH_PRIVATE_KEY_NAME}:ro
            - ~/.composer:/root/.composer
            - /tmpfs
        depends_on:
            - mysql
        ports:
          - 9090:80
        env_file:
            - .env