version: '3.2'

volumes:
  db:
    driver: local
    labels:
      project: magento2
  es:
    driver: local
    labels:
      project: magento2

services:
    magento24-app:
        build:
            context: .
            dockerfile: ./2.4/Dockerfile
        # image: magento2.4-docker:1.1.1
        working_dir: /var/www/app
        container_name: magento-app
        hostname: magento.local
        networks:
            magento:
                aliases:
                - magento.local
        volumes:
            - ${APP_DIR}:/var/www/app
            - ~/.composer:/root/.composer
            - /tmpfs
        depends_on:
            - magento24-db
            - magento24-elasticsearch
        ports:
          - 80:80
        env_file:
            - .env

    magento24-elasticsearch:
        image: elasticsearch:7.8.0
        container_name: magento-es
        hostname: es.magento.local
        networks:
            magento:
                aliases:
                - es.magento.local
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment: 
            - 'discovery.type=single-node'
        volumes:
            - es:/usr/share/elasticsearch/data

    magento24-db:
        image: mysql:latest
        container_name: magento-mysql
        hostname: db.magento.local
        networks:
            magento:
                aliases:
                - db.magento.local
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=magento2

networks:
  magento:
    driver: bridge            