data:
    image: busybox
    volumes:
        - ${PINTUSHI_DIR}:/var/www/pintushi
        - /vendor
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        - ~/.composer:/root/.composer
        - /tmpfs

nginx:
    image: nginx
    links:
        - php
    volumes_from:
        - data
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: pintushi_dev
        MYSQL_USER: pintushi
        MYSQL_PASSWORD: pintushi

php:
    build: php
    working_dir: /var/www/pintushi
    volumes_from:
        - data
    links:
        - mysql
        - memcached
    mem_limit: 2000000000
    env_file:
        - .env

memcached:
    image: memcached

